#!/bin/bash
#
# session_name="dev"
#
# # 1. First you check if a tmux session exists with a given name.
# tmux has-session -t=$session_name 2> /dev/null
#
# # 2. Create the session if it doesn't exists.
# if [[ $? -ne 0 ]]; then
#   TMUX='' tmux new-session -d -s "$session_name"
# fi
#
# # 3. Attach if outside of tmux, switch if you're in tmux.
# if [[ -z "$TMUX" ]]; then
#   tmux attach -t "$session_name"
# else
#   tmux switch-client -t "$session_name"
# fi
#
session_name="dev"

# 1. First you check if a tmux session exists with a given name.
tmux has-session -t=$session_name 2> /dev/null

# 2. Create the session if it doesn't exists.
if [[ $? -ne 0 ]]; then
  TMUX='' tmux new-session -d -s "$session_name"
fi

# 3. Attach if outside of tmux, switch if you're in tmux and the current session is not 'dev'.
if [[ -z "$TMUX" ]]; then
  tmux attach -t "$session_name"
# elif [[ "$(tmux display-message -p '#S')" != "$session_name" ]]; then
#   tmux switch-client -t "$session_name"
fi
# tms start
