#! /bin/sh
#
# Save this script as executable ~/bin/zathist.sh and
# add to ~/.xbindkeysrc the shortcut
#
# "$HOME/bin/zathist.sh"
#   Control + Alt + z
#

# PDFs whose path matches this pattern will not be listed
IGNORE_REGEX="^${TMPDIR:-/tmp}/\|_cropped\.pdf$"
NOTES_PATH=".*/Desktop/notes/.*\.pdf$"

# uses rofi in dmenu mode; replace by dmenu itself at will
PROMPT='❯ '
MENU_ENGINE="rofi"
MENU_ARGS='-dmenu -i -keep-right'

# regex from https://github.com/lucc/config/blob/d416378290d25b9a61cd8252f7ecf98a294dd80f/rofi/bin/mru.sh#L7
selection=$(
    sqlite3 ~/.local/share/zathura/bookmarks.sqlite "select file from fileinfo;" |
    sort -nr | cut -d ' ' -f 2- |
    grep -v "$IGNORE_REGEX" |
    grep -v "$NOTES_PATH" |
    while IFS= read -r f; do [ -f "$f" ] && echo "$f"; done |
    sed "s#^${HOME}/#~/#" |
    ${MENU_ENGINE} ${MENU_ARGS} -p "$PROMPT" |
    sed "s#^~/#${HOME}/#"
)
[ -r "$selection" ] || exit
nohup zathura "$selection" </dev/null >/dev/null 2>&1 &
