vim.cmd("set background=dark")
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.smoothie"
require "user.comment"
require "user.nvim-tree"
-- require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.latex"
-- require "user.project"
--require "user.impatient"
require "user.indentline"
--require "user.alpha"
--require "user.whichkey"
--require "user.autocommands"
require "user.dap"
require "user.rust-tools"
require "user.noice"

vim.cmd("set colorcolumn=88")
