vim.cmd("filetype plugin indent on")
vim.cmd("let g:vimtex_view_general_viewer = 'okular'")
vim.cmd("let g:vimtex_view_method = 'zathura'")
-- vim.cmd("let g:vimtex_compiler_method = 'latexrun'")
vim.cmd("let maplocalleader = '\\'")
